name: Fetch VPNGate API

on:
  schedule:
    # her 15 minutda işleýär
    - cron: '*/15 * * * *'
  workflow_dispatch: # el bilen işledip bolar

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run fetch script
        run: |
          chmod +x scripts/fetch_and_commit.sh
          ./scripts/fetch_and_commit.sh
