name: Avtomatiki Täzelik Push

# Bu workflow diňe main (baş) şahamçasyna işlediler
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Her sagady bir gezek işleýär

permissions:
  contents: write  # GITHUB_TOKEN bilen ýazmaga rugsat berýär

jobs:
  update-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Repo-ny klonla
      uses: actions/checkout@v3

    - name: Script-i işledip täzelik döret
      run: |
        # Mysal üçin bir faýl üýtgedilýär
        echo "Täzelik wagty: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> update_log.txt

    - name: Git konfigurasiýasy
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Üýtgeşmeleri commit et
      run: |
        git add .
        git commit -m "Avtomatiki täzelik $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "Üýtgeşme ýok"

    - name: Üýtgeşmeleri push et
      run: |
        git push origin main
