name: Fetch VPNGate API

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download VPNGate data
        run: |
          mkdir -p data
          curl -k -L "https://www.vpngate.net/api/iphone/" -o data/iphone_api.json
          head -n 20 data/iphone_api.json

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/iphone_api.json
          git diff --quiet && echo "No changes to commit" || (git commit -m "Auto-update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" && git push)
