name: Iphone API Täzelik Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Her sagady bir gezek işleýär

permissions:
  contents: write  # GITHUB_TOKEN bilen ýazmaga rugsat berýär

jobs:
  update-iphone-api:
    runs-on: ubuntu-latest

    steps:
    # Repo-ny klonla
    - name: Checkout repo
      uses: actions/checkout@v3

    # fetch_and_commit.sh script-ini işledip, json-i doldur
    - name: Iphone API script-i işledip json täzeläň
      run: |
        chmod +x ./scripts/fetch_and_commit.sh
        ./scripts/fetch_and_commit.sh

    # Git konfigurasiýasy
    - name: Git konfigurasiýasy
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Üýtgeşmeleri commit et
    - name: Commit üýtgeşmeler
      run: |
        git add data/iphone_api.json
        git commit -m "Avtomatiki täzelik $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "Üýtgeşme ýok"

    # Üýtgeşmeleri push et
    - name: Push üýtgeşmeler
      run: |
        git push origin main
