name: Fetch VPNGate API

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Make script executable
        run: chmod +x scripts/fetch_and_commit.sh

      - name: Run fetch script
        run: ./scripts/fetch_and_commit.sh
